export type CulturalLanguage = 'fra' | 'eng' | 'lin' | 'kit';
export type CulturalEntryType =
  | 'proverb'
  | 'greeting'
  | 'expression'
  | 'cultural_note'
  | 'dialogue';

export interface CulturalEntry {
  id: string;
  type: CulturalEntryType;
  language: CulturalLanguage;
  title: string;
  content: string;
  translation_fr?: string;
  tags: string[];
  source: string;
}

export const CULTURAL_ENTRIES: CulturalEntry[] = [
  // Lingala (13)
  {
    id: 'lin-greeting-001',
    type: 'greeting',
    language: 'lin',
    title: 'Salutation standard',
    content: 'Mbote na yo.',
    translation_fr: 'Bonjour a toi.',
    tags: ['salutation', 'quotidien'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-greeting-002',
    type: 'greeting',
    language: 'lin',
    title: 'Comment ca va',
    content: 'Sango nini?',
    translation_fr: 'Quelles nouvelles ?',
    tags: ['salutation', 'conversation'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-greeting-003',
    type: 'greeting',
    language: 'lin',
    title: 'Reponse tout va bien',
    content: 'Nazali malamu.',
    translation_fr: 'Je vais bien.',
    tags: ['reponse', 'conversation'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-greeting-004',
    type: 'greeting',
    language: 'lin',
    title: 'Bienvenue',
    content: 'Boyei malamu.',
    translation_fr: 'Soyez les bienvenus.',
    tags: ['hospitalite', 'accueil'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-expression-001',
    type: 'expression',
    language: 'lin',
    title: 'Remercier',
    content: 'Matondi mingi.',
    translation_fr: 'Merci beaucoup.',
    tags: ['politesse'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-expression-002',
    type: 'expression',
    language: 'lin',
    title: 'Repondre merci',
    content: 'Ezali mpamba.',
    translation_fr: 'De rien.',
    tags: ['politesse'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-expression-003',
    type: 'expression',
    language: 'lin',
    title: 'Au revoir',
    content: 'Tokomonana lisusu.',
    translation_fr: 'On se reverra.',
    tags: ['depart'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-expression-004',
    type: 'expression',
    language: 'lin',
    title: 'Pardon',
    content: 'Limbisa ngai.',
    translation_fr: 'Pardonne-moi.',
    tags: ['politesse', 'excuse'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-expression-005',
    type: 'expression',
    language: 'lin',
    title: 'Paix',
    content: 'Kimia na ndako na yo.',
    translation_fr: 'Paix dans ta maison.',
    tags: ['benediction'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-proverb-001',
    type: 'proverb',
    language: 'lin',
    title: 'Un seul doigt ne tue pas un pou',
    content: 'Mosapi moko ekokanga te nse.',
    translation_fr: 'Un seul doigt ne peut pas ecraser un pou.',
    tags: ['proverbe', 'solidarite'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-proverb-002',
    type: 'proverb',
    language: 'lin',
    title: 'Un seul arbre ne fait pas la foret',
    content: 'Nzete moko esalaka zamba te.',
    translation_fr: 'Un arbre seul ne fait pas la foret.',
    tags: ['proverbe', 'communaute'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-proverb-003',
    type: 'proverb',
    language: 'lin',
    title: 'Le palmier ne pousse pas vite',
    content: 'Nzembo ekolaka malembe.',
    translation_fr: 'Le bon resultat vient avec le temps.',
    tags: ['proverbe', 'patience'],
    source: 'validated-corpus',
  },
  {
    id: 'lin-dialogue-001',
    type: 'dialogue',
    language: 'lin',
    title: 'Echange de base',
    content: 'A: Mbote. B: Mbote na yo. A: Sango nini? B: Nazali malamu.',
    translation_fr: 'A: Bonjour. B: Bonjour. A: Quoi de neuf ? B: Je vais bien.',
    tags: ['dialogue', 'apprentissage'],
    source: 'validated-corpus',
  },

  // Kituba (13)
  {
    id: 'kit-greeting-001',
    type: 'greeting',
    language: 'kit',
    title: 'Salutation de base',
    content: 'Mbote.',
    translation_fr: 'Bonjour.',
    tags: ['salutation'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-greeting-002',
    type: 'greeting',
    language: 'kit',
    title: 'Comment vas-tu',
    content: 'Nge me kwenda mbote?',
    translation_fr: 'Tu vas bien ?',
    tags: ['salutation', 'conversation'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-greeting-003',
    type: 'greeting',
    language: 'kit',
    title: 'Je vais bien',
    content: 'Mono me kwenda mbote.',
    translation_fr: 'Je vais bien.',
    tags: ['reponse'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-greeting-004',
    type: 'greeting',
    language: 'kit',
    title: 'Bienvenue',
    content: 'Lenda mbote.',
    translation_fr: 'Bienvenue.',
    tags: ['accueil'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-expression-001',
    type: 'expression',
    language: 'kit',
    title: 'Remercier',
    content: 'Matondo mingi.',
    translation_fr: 'Merci beaucoup.',
    tags: ['politesse'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-expression-002',
    type: 'expression',
    language: 'kit',
    title: 'De rien',
    content: 'Kima ve.',
    translation_fr: 'De rien.',
    tags: ['politesse'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-expression-003',
    type: 'expression',
    language: 'kit',
    title: 'Au revoir',
    content: 'Tala nge na nima.',
    translation_fr: 'A plus tard.',
    tags: ['depart'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-expression-004',
    type: 'expression',
    language: 'kit',
    title: 'Excuse',
    content: 'Lemvo.',
    translation_fr: 'Pardon / excuse-moi.',
    tags: ['excuse', 'politesse'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-expression-005',
    type: 'expression',
    language: 'kit',
    title: 'Paix sur toi',
    content: 'Kimia na nge.',
    translation_fr: 'Paix sur toi.',
    tags: ['benediction'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-proverb-001',
    type: 'proverb',
    language: 'kit',
    title: 'Un doigt seul ne lave pas le visage',
    content: 'Munu ya mosi ka sukula ve kizizi.',
    translation_fr: 'Seul, on ne fait pas grand-chose.',
    tags: ['proverbe', 'solidarite'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-proverb-002',
    type: 'proverb',
    language: 'kit',
    title: 'Une seule main n attache pas un paquet',
    content: 'Maboko mosi ka kanga ve nkosi ya biloko.',
    translation_fr: 'La cooperation est necessaire.',
    tags: ['proverbe', 'travail-collectif'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-proverb-003',
    type: 'proverb',
    language: 'kit',
    title: 'Patience donne un bon fruit',
    content: 'Ntangu yina me bikana, me buta mbuma ya mbote.',
    translation_fr: 'La patience porte de bons fruits.',
    tags: ['proverbe', 'patience'],
    source: 'validated-corpus',
  },
  {
    id: 'kit-dialogue-001',
    type: 'dialogue',
    language: 'kit',
    title: 'Dialogue quotidien',
    content: 'A: Mbote. B: Mbote. A: Nge me kwenda mbote? B: Mono me kwenda mbote.',
    translation_fr: 'A: Bonjour. B: Bonjour. A: Tu vas bien ? B: Je vais bien.',
    tags: ['dialogue', 'apprentissage'],
    source: 'validated-corpus',
  },

  // French (5)
  {
    id: 'fra-greeting-001',
    type: 'greeting',
    language: 'fra',
    title: 'Salutation formelle',
    content: 'Bonjour, comment allez-vous ?',
    tags: ['salutation', 'formel'],
    source: 'validated-corpus',
  },
  {
    id: 'fra-expression-001',
    type: 'expression',
    language: 'fra',
    title: 'Bienvenue',
    content: 'Soyez les bienvenus chez nous.',
    tags: ['hospitalite'],
    source: 'validated-corpus',
  },
  {
    id: 'fra-proverb-001',
    type: 'proverb',
    language: 'fra',
    title: 'Patience',
    content: 'Petit a petit, l oiseau fait son nid.',
    tags: ['proverbe', 'patience'],
    source: 'validated-corpus',
  },
  {
    id: 'fra-proverb-002',
    type: 'proverb',
    language: 'fra',
    title: 'Union',
    content: 'L union fait la force.',
    tags: ['proverbe', 'union'],
    source: 'validated-corpus',
  },
  {
    id: 'fra-cultural-note-001',
    type: 'cultural_note',
    language: 'fra',
    title: 'Politesse locale',
    content: 'Dans de nombreux contextes congolais, on salue avant toute demande.',
    tags: ['culture', 'etiquette'],
    source: 'validated-corpus',
  },

  // English (3)
  {
    id: 'eng-greeting-001',
    type: 'greeting',
    language: 'eng',
    title: 'Basic greeting',
    content: 'Hello, how are you today?',
    tags: ['greeting'],
    source: 'validated-corpus',
  },
  {
    id: 'eng-proverb-001',
    type: 'proverb',
    language: 'eng',
    title: 'Community wisdom',
    content: 'If you want to go far, go together.',
    tags: ['proverb', 'community'],
    source: 'validated-corpus',
  },
  {
    id: 'eng-cultural-note-001',
    type: 'cultural_note',
    language: 'eng',
    title: 'Greeting etiquette',
    content: 'In many Congolese communities, greeting first is a sign of respect.',
    tags: ['culture', 'etiquette'],
    source: 'validated-corpus',
  },
];
